### ISSUE TITLE
Adding multiple templates at the same time

### ISSUE THREAD

**Issue by pall-valmundsson** [opinkerfi/okconfig#31]
I would like to be able to do something like this:
`okconfig addtemplate <host> --template <t1>,<t2>,<t3>,<t4>`
and have the four templates applied to the host.

This would save me the time writing for loops.

I'll write the patch; I just need to know where I should put the splitting logic (CLI script or in the library, CLI makes sense, right?). And also the preferred delimiter, it seems logical to use `,` but that would break support for templates with `,` in their name. I don't do that, have you seen it used somewhere? A possible workaround could be to check if the whole template string existed as a template and if not try to split it up and then finally fail if nothing succeeds.

**Comment by ghomem** [comment]
Could this be done also with services, so that we can select "Add Service" from OKConfig's webinterface a select multiple service templates to apply?
