### ISSUE TITLE
adagios reports okconfig problem after successful okconfig verify

### ISSUE THREAD

**Issue by ashirel** [opinkerfi/okconfig#76]
i've installed okconfig from sourceon debian v7 wheezy according to the instructions in
https://github.com/opinkerfi/okconfig#installing-on-rhelcentos
with  nagios3.5.1 and adagios1.4 already installed and running.
the okconfig install seemed successful because the verify succeeded.
however, the adagios 'config health'  reports 'false for 'OKConfig is installed and working'.
where shall i look to determine why adagios reports thusly?

**Comment by merlynix** [comment]
Hello, can you help me?
I'm on Ubuntu 14.04 LTS server TRUSTY , adagios 1.6.1 , 0.7.0-1 pynag , nagios3 , okconfig 2.5, apache2 . I followed the tutorial okconfig plant ( https://github.com/opinkerfi/okconfig#installing-on-rhelcentos ) okconfig but does not. I have a 404 mynameserver / adagios / okconfig . J have checked the files conf and okconfig verify everything is OK but I have not the okconfig adagios menu on the page.

**Comment by gardart** [comment]
Please reopen this issue if you still need help with this
