### ISSUE TITLE
Additional functionlity to okconfig?

### ISSUE THREAD

**Issue by spicysomtam** [opinkerfi/okconfig#81]
It would be very useful to remove services from hosts via okconfig command. For example, we have a linux example template that is added to hosts, but some of the checks are invalid, depending on what the host is used for. Thus the ability to remove services that are not valid (eg diskspace check for /oracle if the server doesn't have an /oracle filesystem). We could even make the failed check do the service removal for the host, so there is no need for manual intervention! But we would need the functionality via okconfig (or maybe we can do it via pynag?).

Able to filter hosts via group with the listhosts option. That would save piping the output into awk/grep/etc.

Remove a host and all its services.

Reload nagios.

I am sure there are more, but okconfig is a pretty good way to do mass updates. A simple example is we add a service check to the linux template. Then we want to add that check to all linux hosts (which would be in the linux-<site> group).

**Comment by hakong** [comment]
>It would be very useful to remove services from hosts via okconfig command.

```
pynag delete where object_type=service and host_name=host.domain.com and register=1 and service_description="Disk /oracle"
```

>We could even make the failed check do the service removal

This sounds like a horrible idea :frowning: I would never want a service check that runs every x minutes doing any circus tricks in my nagios config.

>Able to filter hosts via group with the listhosts option. That would save piping the output into awk/grep/etc.

```
pynag list host_name contact_groups host_groups where register=1 object_type=host
pynag list --seperator=, --quiet host_name contact_groups host_groups where register=1 object_type=host 
```

>Remove a host and all its services.

```
pynag delete where host_name=host.domain.com
```

>A simple example is we add a service check to the linux template. Then we want to add that check to all linux hosts

Meh, pynag again :smile:

**Comment by spicysomtam** [comment]
Thanks hakong; I will get to know pynag instead :)
