### ISSUE TITLE
CentOS 7 "could not detect distribution"

### ISSUE THREAD

**Issue by eroji** [opinkerfi/okconfig#82]
I am trying to use okconfig to install NRPE agent on CentOS 7 server but the script is failing with the error "could not detect distribution. Exiting...".

Here are the os-release info:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by pall-valmundsson** [comment]
This was fixed in 1e6e6744568d5af427ecebdfdb3f2c4139992a3a which isn't in a tagged release. You could try to install the latest test package.

How about tagging a new release? @tomas-edwardsson @palli

**Comment by gardart** [comment]
There is a now a new tagged release that includes 1e6e674
