### ISSUE TITLE
Problem with check_dns after updating to nagios-plugins-dns-2.0.3-3

### ISSUE THREAD

**Issue by gardart** [opinkerfi/okconfig#84]
After update nagios-plugins-dns-2.0.3-3.el6.x86_64 check_dns gives another output and appends name = in front of the hostname

**Temporary fix:**

define service {
        use                     generic-service
	name                          okc-check_forward_lookup
        service_description     Reverse Lookup
	check_command                 okc-check_dns!$HOSTADDRESS$!"name = $HOSTNAME$."
	 register                       0
}

**Comment by hakong** [comment]
Shouldn't we just report this bug? Have the package maintainer fix it?

**Comment by gardart** [comment]
If this is really a bug then I aggree @hakong. I havent tested this update, only seen this happen on one machine. Did you ran into this problem as well after updating this plugin?

**Comment by hakong** [comment]
Yep, 2 customers of ours had this problem and we too.

**Comment by gardart** [comment]
ok, I will report this bug to the maintainer

**Comment by gardart** [comment]
Issue created here:
https://github.com/nagios-plugins/nagios-plugins/issues/223

**Comment by gardart** [comment]
Fixed with https://github.com/opinkerfi/okconfig/pull/91
