### ISSUE TITLE
How do I add a new template ? 

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/okconfig#98]
Hi 
I can't figure out how to create a new template(ex. for IPMI devices) ?
I clone an existing template in /usr/share/okconfig/templates/linux directory into /usr/share/okconfig/templates/ipmi.
But the okconfig listtempaltes wouldn't list out the hew ipmi template ?
How do I register the newly clone ipmi template ? 

R1: https://github.com/opinkerfi/okconfig/tree/master/usr/share/okconfig/templates

**Comment by hakong** [comment]
Try creating the template in /etc/nagios/okconfig/examples. This is where I keep all my custom templates.

**Comment by pall-valmundsson** [comment]
The templating of hosts is done using the `.cfg-example` files. Try to copy the linux.cfg-example directory into /etc/nagios/okconfig/examples directory as ipmi.cfg-example and go from there.

ps. a poorly documented feature is that you can override the global templates in /usr/share/okconfig/examples by having an example file of the same name in the /etc/nagios/okconfig/examples, that way changes won't revert if you update the okconfig package.

**Comment by tjyang** [comment]
cancel above bad question, "192.168.11.18" is filled by nslookup.
